"""Official Python client and CLI for the Arbitr External API."""

from arbitr._constants import (
    ACTION_REQUIRED_STATUSES,
    ALLOWED_UPLOAD_EXTENSIONS,
    DEFAULT_BASE_URL,
    MAX_UPLOAD_FILES,
    MAX_UPLOAD_TOTAL_BYTES,
    SUPPORTED_FORMATS,
    TERMINAL_STATUSES,
)
from arbitr._projects import ProjectResumptionResponse
from arbitr._spec import OpenAPIDocumentError, pinned_spec
from arbitr._version import __version__
from arbitr.async_client import AsyncArbitrClient
from arbitr.client import ArbitrClient, new_idempotency_key
from arbitr.errors import (
    ActionRequiredError,
    AmbiguousLocaleCodesError,
    ArbitrBaseError,
    ArbitrClientError,
    ArbitrError,
    AuthenticationError,
    BareLocaleCodeError,
    ClientInputError,
    ConflictError,
    ConnectionFailedError,
    DisallowedFileExtensionError,
    GoneError,
    MissingApiKeyError,
    NotFoundError,
    PaymentRequiredError,
    ProjectWaitTimeoutError,
    RateLimitError,
    RequestTimeoutError,
    ResponseDecodeError,
    ResponseParseError,
    ServerError,
    TransportError,
    UnknownLocaleCodesError,
    ValidationError,
)
from arbitr.generated.models import (
    CreditBalanceResponse,
    DeliverableListResponse,
    HumanReviewResponse,
    LanguageListResponse,
    LanguageResponse,
    MeResponse,
    Page,
    ProjectDeliverableResponse,
    ProjectListResponse,
    ProjectResponse,
)
from arbitr.webhooks import (
    KNOWN_EVENTS,
    WebhookVerificationError,
    compute_signature,
    parse_event,
    verify_signature,
)

__all__ = [
    "ACTION_REQUIRED_STATUSES",
    "ALLOWED_UPLOAD_EXTENSIONS",
    "DEFAULT_BASE_URL",
    "KNOWN_EVENTS",
    "MAX_UPLOAD_FILES",
    "MAX_UPLOAD_TOTAL_BYTES",
    "SUPPORTED_FORMATS",
    "TERMINAL_STATUSES",
    "ActionRequiredError",
    "AmbiguousLocaleCodesError",
    "ArbitrBaseError",
    "ArbitrClient",
    "ArbitrClientError",
    "ArbitrError",
    "AsyncArbitrClient",
    "AuthenticationError",
    "BareLocaleCodeError",
    "ClientInputError",
    "ConflictError",
    "ConnectionFailedError",
    "CreditBalanceResponse",
    "DeliverableListResponse",
    "DisallowedFileExtensionError",
    "GoneError",
    "HumanReviewResponse",
    "LanguageListResponse",
    "LanguageResponse",
    "MeResponse",
    "MissingApiKeyError",
    "NotFoundError",
    "OpenAPIDocumentError",
    "Page",
    "PaymentRequiredError",
    "ProjectDeliverableResponse",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectResumptionResponse",
    "ProjectWaitTimeoutError",
    "RateLimitError",
    "RequestTimeoutError",
    "ResponseDecodeError",
    "ResponseParseError",
    "ServerError",
    "TransportError",
    "UnknownLocaleCodesError",
    "ValidationError",
    "WebhookVerificationError",
    "__version__",
    "compute_signature",
    "new_idempotency_key",
    "parse_event",
    "pinned_spec",
    "verify_signature",
]
